source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'HPXibDesignableObjC_Example', :exclusive => true do
  pod "HPXibDesignableObjC", :path => "../"
end

target 'HPXibDesignableObjC_Tests', :exclusive => true do
  pod "HPXibDesignableObjC", :path => "../"

  
end
